---
extends:
  - 'stripe'
  - plugin:flowtype/recommended
  - 'prettier'
  - 'prettier/flowtype'
  - 'prettier/react'
rules:
  import/no-dynamic-require: 0
  no-plusplus: 0
  no-duplicate-imports: 0
env:
  jest: true
parser: 'babel-eslint'
plugins:
  - 'flowtype'
